using System.Windows;using System.Windows.Controls;using DBACheck2.App.Models;using DBACheck2.App.Services;
namespace DBACheck2.App;
public partial class IncidentOperationsWindow:Window
{
 private readonly IncidentOperationsService _ops; private readonly SqlHealthService _sql; private bool En=>LocalizationService.Current==AppLanguage.En;
 public IncidentOperationsWindow(SqlHealthService sql){InitializeComponent();_sql=sql;_ops=new(sql);ApplyLanguage();Loaded+=async(_,__)=>await LoadAsync();}
 private void ApplyLanguage(){TitleText.Text=En?"INCIDENT OPERATIONS":"OPERACIONES DE INCIDENTES";DatabaseColumn.Header=En?"Database":"Base";ModuleColumn.Header=En?"Module":"Módulo";SeverityColumn.Header=En?"Severity":"Sev";CountColumn.Header=En?"Count":"Veces";ProblemColumn.Header=En?"Problem":"Problema";AnalyzeButton.Content=En?"CORRELATE":"CORRELACIONAR";ReportButton.Content=En?"TECHNICAL REPORT":"REPORTE TÉCNICO";VerifyButton.Content=En?"REVALIDATE":"REVALIDAR";JobButton.Content=En?"JOB PLAYBOOK":"PLAYBOOK: JOB";DetailText.Text=En?"Select an OPEN incident.":"Seleccioná un incidente OPEN.";}
 private IncidentOperationSummary? Selected=>GridIncidents.SelectedItem as IncidentOperationSummary;
 private async Task LoadAsync(){var x=await _ops.OpenAsync();GridIncidents.ItemsSource=x;SummaryText.Text=En?$"Beta 1 · {x.Count} OPEN incident(s) · Incident Center · Evidence · Safe Playbooks":$"Beta 1 · {x.Count} incidente(s) OPEN · Centro de incidentes · Evidencia · Playbooks seguros";}
 private void GridIncidents_SelectionChanged(object s,SelectionChangedEventArgs e){var on=Selected!=null;AnalyzeButton.IsEnabled=ReportButton.IsEnabled=VerifyButton.IsEnabled=on;JobButton.IsEnabled=on&&Selected!.Module=="Transaction Log";}
 private async void AnalyzeButton_Click(object s,RoutedEventArgs e){if(Selected is{}x)DetailText.Text=await _ops.BuildIncidentCenterAsync(x);}
 private async void ReportButton_Click(object s,RoutedEventArgs e){if(Selected is{}x){var t=await _ops.BuildTechnicalReportAsync(x);DetailText.Text=t;Clipboard.SetText(t);StatusText.Text=En?"Technical report copied to clipboard.":"Reporte técnico copiado al portapapeles.";}}
 private async void VerifyButton_Click(object s,RoutedEventArgs e){if(Selected is not{}x)return;if(x.Module=="Transaction Log"){var logs=await _sql.GetLogDatabasesAsync();var z=logs.FirstOrDefault(a=>a.DatabaseName.Equals(x.DatabaseName,StringComparison.OrdinalIgnoreCase));DetailText.Text=z==null?(En?"Database not found.":"Base no encontrada."):$"REVALIDATION - {z.DatabaseName}\nStatus: {z.Status}\nUsed: {z.UsedPct:0.0}%\nReuse Wait: {z.ReuseWait}\n\n{(En?"READ-ONLY - no action was executed.":"SOLO LECTURA - no se ejecutó ninguna acción.")}";}}
 private void JobButton_Click(object s,RoutedEventArgs e){if(Selected is not{}x)return;DetailText.Text=En?$"SAFE PLAYBOOK - SQL AGENT JOB\nDatabase: {x.DatabaseName}\n\nBeta 1 does not execute an ambiguous job automatically.\n1. Review Job/Step correlation.\n2. Explicitly select the correct job in Backups / Jobs.\n3. Capture evidence.\n4. Confirm manual/controlled execution.\n5. Revalidate the incident.\n\nSAFETY: no job was executed.":$"PLAYBOOK SEGURO - SQL AGENT JOB\nBase: {x.DatabaseName}\n\nBeta 1 no ejecuta un job ambiguo automáticamente.\n1. Revisar correlación Job/Step.\n2. Seleccionar explícitamente el job correcto en Backups / Jobs.\n3. Capturar evidencia.\n4. Confirmar ejecución manual/controlada.\n5. Revalidar el incidente.\n\nSEGURIDAD: no se ejecutó ningún job.";StatusText.Text=En?"Playbook prepared; no action executed.":"Playbook preparado; ninguna acción ejecutada.";}
    private void ExpandDetailButton_Click(object sender,RoutedEventArgs e)=>DetailPanelService.Toggle(ListRow,DetailRow,ExpandDetailButton,125,105);
}